# This is a basic workflow that is manually triggered

name: Manual update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Branch to run against'
        # Default value if no value is explicitly provided
        default: 'gh-actions-test'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Build new version
      run: |
        cur_version=$(grep 'WatchNixtoons2" version' addon.xml | cut -f4 -d " " | cut -c 10- | cut -c -4)
        new_version=$(echo $cur_version | awk '{print $1+0.01}')
        if [[ ${{ github.event.inputs.name }} == "master" ]]; then
          branch=""
        else
          branch=".${{ github.event.inputs.name }}"
        fi
        mkdir plugin.video.watchnixtoons2${branch}
        cp addon.xml Default.py *.jpg *.png plugin.video.watchnixtoons2.kodi19/.
        cp -R Lib/ plugin.video.watchnixtoons2.kodi19/
        cp -R resources/ plugin.video.watchnixtoons2${branch}/
        zip -9 -r ./plugin.video.watchnixtoons2${branch}-${new_version}.zip plugin.video.watchnixtoons2.kodi19/
        rm -rf plugin.video.watchnixtoons2${branch}
